
# Список Вендоров
vendor_list:
  entity: 'vendorList'
  handler: 'vendorList'
  view:
    form: 'Data\VendorList\Form'
    table: 'Data\VendorList\Table'
    box: 'Data\VendorList\Box'
    json: 'Data\VendorList\Json'

#--------------------------------------------